
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EcommerceShop.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Brand
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tbl_Brand()
    {

        this.Tbl_Product = new HashSet<Tbl_Product>();

    }


    public int BrandId { get; set; }

    public string BrandName { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<int> MemberId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tbl_Product> Tbl_Product { get; set; }

    public virtual Tbl_Members Tbl_Members { get; set; }

}

}
