
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EcommerceShop.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Transaction
{

    public int TransactionId { get; set; }

    public Nullable<int> MemberId { get; set; }

    public Nullable<int> StoreId { get; set; }

    public Nullable<int> ProductId { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<decimal> TotalAmount { get; set; }

    public Nullable<System.DateTime> TimeStamp { get; set; }



    public virtual Tbl_Product Tbl_Product { get; set; }

    public virtual Tbl_Store Tbl_Store { get; set; }

    public virtual Tbl_Members Tbl_Members { get; set; }

}

}
